name: Container Workflow
on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'Enter image name'
        required: true
      acr-server:
        description: 'Enter ACR server name'
        required: true
      client-id:
        description: 'Enter Service Principal Client Id'
        required: true
      client-secret:
        description: 'Enter Service Principal Client Secret'
        required: true
jobs:
  build-image:
    env:
      server-image-path: ${{ format('{0}/{1}', github.event.inputs.acr-server, github.event.inputs.image-name) }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List files in GitHub workspace
        run: ls ${{ github.workspace }}
      - name: Check Docker file existence
        id: check-docker-file
        uses: andstor/file-existence-action@v1
        with:
          files: "sample-mvc-docker-app/Dockerfile"
      - name: File exists
        if: steps.check-docker-file.outputs.files_exists != 'true'
        run: exit 1
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.server-image-path }}
          username: ${{ github.event.inputs.client-id }}
          password: ${{ github.event.inputs.client-secret }}
      - name: Build image
        run: docker build ./sample-mvc-docker-app -t ${{ github.event.inputs.image-name }}
      - name: Tag Image
        run: docker tag ${{ github.event.inputs.image-name }} ${{ env.server-image-path }}
      - name: Push image
        run: docker push ${{ env.server-image-path }}
