name: Matrix Testing for Jobs
on: workflow_dispatch
jobs:
  Build-Code:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        dotnet-version: [3.x, 5.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Environment details
        run: echo "This is running on ${{ matrix.os }} with dotnet version ${{ matrix.dotnet-version }}"
        
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
    
