name: Workflows requiring approval
on:
  workflow_dispatch: 

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First workflow ran successfully"
  
  second-workflow:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: This is waiting to run based on approval
        run: echo "Second workflow ran successfully ${{ vars.MYVAR }}"
